# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ae62d63fcc36c9b88c108c57db642ad637f1520273c4bca85b19f20c180a2143dfad7fb8768871ea31cf599a280b199c44b67490ea74ed8f36eb2ab27a89719

test:
  secret_key_base: 41824540b2efaed549e85029d34c40a4acafc468e2206c502026b40fee0b374b8b9969793720208dd4f5f539c2f093b72e1e21fe967fcd2d8268a156bca38528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
